##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://test.ibdsr.cn:3030/srsczx?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root123
    filters: log4j,wall,mergeStat

#多数据源
guns:
  muti-datasource:
    default-dataSource-name: dataSourceGuns #默认的数据源名称
    url: jdbc:mysql://172.16.0.251:3306/ibdsr?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root123
  #fastdfs文件上传
  fastDfs-url:
    trackers: 172.16.0.200:22122
    visit: http://fastdfs.ibdsr.cn/  #文件访问的URL包括端口信息

#个人中心菜单id
userinfo:
  menu:
    id: 168